title: HaiAI Blog
tagline: "Chia sẻ ứng dụng & xu hướng Trí tuệ nhân tạo"
description: "Blog cập nhật kiến thức, công cụ và phân tích về AI"
url: "https://nmhai79.github.io"
baseurl: "/haiai"
lang: vi
theme: jekyll-theme-chirpy

author:
  name: Hai
  email: your@email.com
